#############################################################
## NOT FOR PRODUCTION USE.                                 ##
## THE CONTENT OF THIS FILE IS FOR LEARNING PURPOSES ONLY  ##
## created by David Surey, Amazon Web Services, 2020       ##
#############################################################

- name: Destroy Amazon EKS example deployments
  hosts: localhost
  gather_facts: no

  vars: 
    ansible_ssh_private_key_file: "./secrets/id_rsa_eks"
    ansible_user: ec2-user
    
  vars_prompt:
    - name: "security_check"
      prompt: "Do really want to DESTROY your example deployment (yes/no)?"
      private: no

  tasks:
    - name: check if we're gonna destroy
      when: not security_check | bool
      fail:
        msg: cancelled

    - name: check ansible version
      when: (ansible_version.major == 2 and ansible_version.minor < 10 ) or (ansible_version.major < 2)
      run_once: yes
      fail:
        msg: Please use Ansible 2.10 or newer

    - name: import static var data
      include_vars:
        dir: ../../vars/static
        ignore_unknown_extensions: True
        extensions:
          - yaml

    - name: import dynamic var data
      include_vars:
        dir: ../../vars/dynamic
        ignore_unknown_extensions: True
        extensions:
          - yaml

    - name: Get AWS Account Information
      delegate_to: "{{ EKSBastionInstancePublicIP }}"
      aws_caller_info:
      register: caller_info

    - name: delete eksdemo namespace
      delegate_to: "{{ EKSBastionInstancePublicIP }}"
      community.kubernetes.k8s: 
        state: absent
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: eksdemo