apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eksdemo-frontend
  namespace: eksdemo
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/certificate-arn: "{{ eksexamplesslarn }}"
    external-dns.alpha.kubernetes.io/hostname: eksdemo."{{ eksexample_hostedzonename }}"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: eksdemo-frontend
            port:
              number: 80
